### ISSUE TITLE
请问中转的组转能实现点对网吗

### ISSUE THREAD

**Issue by pizixi** [xieyuhua/easy-tun#1]

**Comment by xieyuhua** [comment]
你说的是这个意思吗？
https://github.com/xieyuhua/tun2socks

**Comment by pizixi** [comment]
不是，我说的是这个仓库下的server和client下的异地组网之后，能不能访问对方真实网段的服务器，目前只能访问对方的虚拟网卡吧，点对点

**Comment by xieyuhua** [comment]
对，目前只能通过虚拟网卡访问本机的服务

**Comment by pizixi** [comment]
可有打算支持

**Comment by xieyuhua** [comment]
暂时没有，没思路

**Comment by xieyuhua** [comment]
a是公司内网机器，虚拟10.10.10.1，内网IP是192.168.9.10

b是公司内网机器，内网IP是192.168.9.12

c是家里电脑，虚拟10.10.10.2

目的: a,c都运行了客户端client，想要实现家里电脑，访问公司电脑，192.168.9.12

需要a机器（跳板机）执行，ens32是内网网卡名称    
iptables -t nat -A POSTROUTING  -o ens32 -s 10.10.10.0/24 -j MASQUERADE

需要是家里电脑（客户端c）执行    
ip route add 192.168.9.0/24 via 10.10.10.1

然后就可以执行    
ping 192.168.9.12
